@URL = http://localhost:3000/api

GET {{URL}}/autores

###
GET {{URL}}/autores/5

###
GET {{URL}}/autores/1/posts

###
POST {{URL}}/autores
Content-Type: application/json

{
    "nombre": "Gaizka",
    "email": "gaizka3@gmail.com",
    "imagen": "http://example"
}

###
GET {{URL}}/posts

###
GET {{URL}}/posts/sdafsd

###
POST {{URL}}/posts
Content-Type: application/json

{
    "autores_idautores": "2",
    "titulo": "Titulito300",
    "descripcion": "Una descripcion cualquiera",
    "categoria": "Clasico"
}